package com.brianeno.statemachine.domain;

public enum VehicleStates {

    VEHICLE_SOLD,
    VEHICLE_SPECIFIED,
    FORK_BEGIN_ASSEMBLY,
    VEHICLE_INTERIOR_ASSEMBLING,
    VEHICLE_INTERIOR_ASSEMBLED,
    VEHICLE_EXTERIOR_ASSEMBLING,
    VEHICLE_EXTERIOR_ASSEMBLED,
    JOIN_END_ASSEMBLY,
    VEHICLE_PACKAGED,
    VEHICLE_SHIPPED
}
